### ISSUE TITLE
build failed with asf 3.50.0

### ISSUE THREAD

**Issue by Habraken** [openthread/ot-samr21#46]
The console output at the point of failure is:

Building C object third_party/m...esh/source/phy/at86rf233/src/phy.c.obj
FAILED: third_party/microchip/CMakeFiles/samr21-driver.dir/asf/thirdparty/wireless/avr2130_lwmesh/source/phy/at86rf233/src/phy.c.obj 
...
...
./third_party/microchip/asf/thirdparty/wireless/avr2130_lwmesh/source/phy/at86rf233/src/phy.c:175:2: note: in expansion of macro 'TRX_TRIG_DELAY'
  175 |  TRX_TRIG_DELAY();
      |  ^~~~~~~~~~~~~~
[6/18] cd /Users/Habraken/src/ot-samr2...amr21/openthread/etc/cmake/print.cmake
OPENTHREAD_CONFIG_ASSERT_ENABLE=1
OPENTHREAD_CONFIG_BACKBONE_ROUTER_DUA_NDPROXYING_ENABLE=0
OPENTHREAD_CONFIG_BACKBONE_ROUTER_MULTICAST_ROUTING_ENABLE=0
OPENTHREAD_CONFIG_ENABLE_BUILTIN_MBEDTLS=1
OPENTHREAD_CONFIG_ENABLE_BUILTIN_MBEDTLS_MANAGEMENT=1
OPENTHREAD_CONFIG_PING_SENDER_ENABLE=1
OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1
OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=0
PACKAGE_NAME=OPENTHREAD
PACKAGE_VERSION=0.01.00
OPENTHREAD_CONFIG_THREAD_VERSION=OT_THREAD_VERSION_1_2
OPENTHREAD_CONFIG_NCP_HDLC_ENABLE=1
MBEDTLS_USER_CONFIG_FILE=samr21-mbedtls-config.h
OPENTHREAD_CONFIG_FILE=openthread-core-samr21-config.h
OPENTHREAD_PROJECT_CORE_CONFIG_FILE=openthread-core-samr21-config.h
OPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=openthread-core-samr21-config-check.h
ninja: build stopped: subcommand failed.

I have no idea, what is wrong.

**Comment by jwhui** [comment]
The current SAMR21 example is bound to ASF v3.36 - see [third_party/microchip/README.md](https://github.com/openthread/ot-samr21/blob/main/third_party/microchip/README.md).

OpenThread is an open source project and we would gladly accept contributions to support a newer ASF version.

**Comment by Habraken** [comment]
Thank you for the clarification. I have located the place where you can download archived versions of the ASF: [link](https://www.microchip.com/mplab/avr-support/avr-and-sam-downloads-archive)
I will have a look if I can find the issue(s) with the current release of ASF, but this might be beyond my skill level for the time being.

**Comment by manup** [comment]
If anybody stumbles over this the archive link for older ASF versions has changed:

https://www.microchip.com/en-us/tools-resources/archives/avr-sam-mcus
