### ISSUE TITLE
build failed with ASF 3.36.2

### ISSUE THREAD

**Issue by Habraken** [openthread/ot-samr21#49]
I have tried to build the cli example again, this time with ASF 3.36 version as suggested. It fails however at the same point:

../third_party/microchip/asf/thirdparty/wireless/avr2130_lwmesh/source/phy/at86rf233/src/phy.c:175:2: note: in expansion of macro 'TRX_TRIG_DELAY'
  175 |  TRX_TRIG_DELAY();
      |  ^~~~~~~~~~~~~~
[596/612] Building C object third_part...s/services/trx_access/trx_access.c.obj
ninja: build stopped: subcommand failed.

**Comment by jwhui** [comment]
I just checked the build script and it appears to be using ASF 3.45. The build script works in GitHub Actions: https://github.com/openthread/ot-samr21/actions

Can you try with a clean clone and just use `./script/build` command? That should automatically download ASF 3.45 - see [script/build](https://github.com/openthread/ot-samr21/blob/7abf48265b36c4d8b7d273b81a5958b739ab663f/script/build#L46).

**Comment by Habraken** [comment]
I tried your suggestion. I started with a fresh clone and the script downloaded the ASF 3.45 and ran all the way to the end this time. I count that as a provisional success. Thank you!

**Comment by jwhui** [comment]
@Habraken , great to hear. Thanks. Closing this issue.
