### ISSUE TITLE
Suggestion to help beginners...

### ISSUE THREAD

**Issue by Habraken** [openthread/ot-samr21#57]
I would like to suggest a slight change to the README.md of the OpenThread on SAMR21 Example to help beginners that are not so familiar with OpenOCD. My suggestions is to include a hint that after the OpenOCD server is started with 

$ openocd -f board/atmel_samr21_xplained_pro.cfg

the other commands need to be entered in a new terminal:

$ cd <path-to-ot-samr21>/build/bin
$ arm-none-eabi-gdb ot-cli-ftd
$ (gdb) etc, etc...

It wasn't obvious for me...

**Comment by Kristian8606** [comment]
Can you provide me with a compiled `bin` file?

**Comment by jwhui** [comment]
@Habraken , thanks for raising this issue. Feel free to submit a PR to update the `README.md` if you like.
